name: Publish Package to npm

on:
  workflow_dispatch: # manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.18'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run c:test
      - run: npm run c:lint
      - run: npm run c:format
      - run: npm run c:pack

      - run: npm publish
